// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCrud.Data.Context;

namespace SimpleCrud.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210120220204_Version0001")]
    partial class Version0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleCrud.Domain.Models.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("QuantidadeFuncionarios")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nome = "Apple",
                            QuantidadeFuncionarios = 2,
                            Site = "www.apple.com"
                        },
                        new
                        {
                            Id = 2L,
                            Nome = "Google",
                            QuantidadeFuncionarios = 55,
                            Site = "www.google.com"
                        },
                        new
                        {
                            Id = 3L,
                            Nome = "Microsoft",
                            QuantidadeFuncionarios = 120,
                            Site = "www.microsoft.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
